name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout skewheap
      uses: actions/checkout@v2

    - name: find latest version of janet
      uses: oprypin/find-latest-tag@v1
      id: janet-ver
      with:
        repository: janet-lang/janet
        releases_only: true
        prefix: 'v'

    - name: download janet
      run: curl -LO https://github.com/janet-lang/janet/archive/${{ steps.janet-ver.outputs.tag }}.tar.gz

    - name: extract janet
      run: tar zxvf ${{ steps.janet-ver.outputs.tag }}.tar.gz

    - name: list directory contents
      run: echo $(pwd) && ls -Rls

    - name: install janet
      run: cd janet-${{ steps.janet-ver.outputs.tag }} && make install && cd ..

    - name: run tests
      run: /usr/bin/env jpm test
