name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout skewheap
      uses: actions/checkout@v2

    - name: build test image
      run: docker build -t test-skewheap .

    - name: run test suite
      run: docker run test-skewheap
