name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout skewheap
      uses: actions/checkout@v2

    - name: find latest version of janet
      uses: oprypin/find-latest-tag@v1
      id: janet-ver
      with:
        repository: janet-lang/janet
        releases_only: true
        prefix: 'v'

    - name: download janet
      run: curl -LO https://github.com/janet-lang/janet/releases/download/v1.9.1/janet-v1.9.1-linux.tar.gz

    - name: extract janet
      run: tar -xvzf janet-v1.9.1-linux.tar.gz

    - name: add directory to path
      run: echo "::add-path::janet-v1.9.1-linux"

    - name: install deps
      run: /usr/bin/env jpm deps

    - name: run tests
      run: /usr/bin/env jpm test
